# -*- coding: utf-8 -*-
"""Grafos-PLN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ct6EiQIvTK9uUPaW-qu2QPgZX8yCDVF6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx

"""**Carregamento da Base de Dados**

O dataset `school_performance.csv` foi carregado utilizando `pandas`.

Em seguida:
- verificamos os nomes das colunas
- visualizamos as primeiras linhas da base
"""

dados = pd.read_csv('school perfomance.csv', sep=';')

print(dados.columns)
print(dados.head())

dados.head()

"""**Definição da Variável Alvo**

Foi criada uma variável chamada `y`, representando o risco acadêmico do aluno com base na nota final (`G3`).

Critério adotado:
- Nota menor que 10 = baixo desempenho
- Nota maior ou igual a 10 e menor ou igual a 14 = médio desempenho
- Nota maior ou igual a 15 e menor ou igual a 20 = ótimo desempenho

Essa transformação simplifica a análise em 3 categorias.
"""

def classificar_nota(nota):
    if nota < 10:
        return 'Baixo'
    elif nota < 15:
        return 'Médio'
    else:
        return 'Alto'

dados['categoria'] = dados['G3'].apply(classificar_nota)

"""**Distribuição da Variável Alvo**

Nesta etapa, verificamos a quantidade de alunos aprovados e em risco acadêmico.

Isso ajuda a entender:
- o equilíbrio das classes
- a distribuição dos resultados acadêmicos na base
"""

print(dados['categoria'].value_counts())

"""**Seleção das Características dos Alunos**

Foram selecionadas variáveis numéricas relevantes para medir similaridade entre alunos:

- notas (`G1`, `G2`, `G3`)
- tempo de estudo (`studytime`)
- faltas (`absences`)
- reprovações (`failures`)
- vida social e hábitos (`goout`, `freetime`, `Walc`, `Dalc`)

Essas características serão usadas para construir a rede de similaridade.
"""

#escolher atributos numericos semelhantes
features = dados[['G1','G2',
                  'studytime',
                  'failures',
                  'absences',
                  'goout',
                  'freetime',
                  'Walc',
                  'Dalc']]

"""**Normalização dos Dados**

As variáveis possuem escalas diferentes.

Por exemplo:
- faltas podem chegar a valores altos
- consumo de álcool varia apenas entre 1 e 5

Por isso, aplicamos a padronização com `StandardScaler`, garantindo que todas as variáveis tenham o mesmo peso na análise de similaridade.
"""

#as variavies tem escalas diferentes, normalizar para terem o mesmo peso
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(features)

"""**Cálculo da Similaridade entre Alunos**

Utilizamos a similaridade do cosseno (`cosine similarity`) para medir o quão parecidos os alunos são entre si.

A similaridade varia entre:
- `1` → alunos muito semelhantes
- `0` → sem relação
- valores negativos → perfis diferentes

O resultado é uma matriz onde cada posição representa a similaridade entre dois alunos.
"""

#medindo o quão parecidos são os alunos
from sklearn.metrics.pairwise import cosine_similarity

similaridade = cosine_similarity(X)

print(similaridade)

"""##Criação dos Grafos

**Construção do Grafo**

Foi criado um grafo utilizando a biblioteca `NetworkX`.

Na rede:
- cada aluno representa um nó
- conexões representam semelhança entre alunos

Isso permite transformar os dados em uma estrutura de rede para análise visual e relacional.
"""

G = nx.Graph()

#adicionar nó
for i in range(len(dados)):
  G.add_node(i)

#cada aluno vira um nó

"""**Criação das Conexões entre os Alunos**

Definimos um limite de similaridade (`threshold = 0.75`).

Se dois alunos possuem similaridade maior que 0.75:
- uma aresta é criada entre eles

Assim, somente alunos com perfis realmente parecidos ficam conectados na rede.
"""

for i in range(len(dados)):
    G.add_node(i)

threshold = 0.75

for i in range(len(dados)):
    for j in range(i+1, len(dados)):
        if similaridade[i][j] > threshold:
            G.add_edge(i, j, weight=similaridade[i][j])

"""**Informações da Rede**

Nesta etapa, exibimos:
- quantidade de nós (alunos)
- quantidade de arestas (conexões)

Essas métricas ajudam a entender:
- o tamanho da rede
- o nível de conectividade entre os estudantes
"""

print("Nós:", G.number_of_nodes())
print("Arestas:", G.number_of_edges())

"""**Detecção de Comunidades**

O algoritmos de detecção de comunidades identificou diferentes grupos naturais de alunos dentro da rede.

Esses grupos representam estudantes com características semelhantes em relação a:
* desempenho acadêmico
* tempo de estudo
* faltas
* comportamento social

As maiores comunidades representam os padrões  mais comuns presentes no conjunto de dados.
"""

#agrupa automaticamente os alunos que são semelhantes
from networkx.algorithms.community import greedy_modularity_communities

comunidades = list(greedy_modularity_communities(G))

for i, comunidade in enumerate(comunidades):
    print(f'Comunidade {i}: {len(comunidade)} alunos')

#alunos isolados - possível risco
isolados = list(nx.isolates(G))
print(isolados)

"""**Visualização do Grafo**

O grafo foi desenhado utilizando `matplotlib`.

Interpretação:
- nós próximos representam alunos com características semelhantes
- grupos mais densos indicam comunidades de alunos parecidos
- nós isolados representam alunos com perfil diferente da maioria

Essa visualização permite identificar padrões de comportamento e desempenho acadêmico.
"""

cores = []

for node in G.nodes():
    categoria = dados.loc[node, 'categoria']

    if categoria == 'Baixo':
        cores.append('red')
    elif categoria == 'Médio':
        cores.append('yellow')
    else:
        cores.append('green')

plt.figure(figsize=(12,8))

nx.draw(
    G,
    node_color=cores,
    node_size=40,
    with_labels=False
)

plt.scatter([], [], c='red', label='Baixo')
plt.scatter([], [], c='yellow', label='Médio')
plt.scatter([], [], c='green', label='Alto')

plt.legend()
plt.show()

"""**Interpretação do Grafo 1**

Na visualização da rede, cada nó representa um aluno e cada conexão representa alta similaridade entre seus perfis acadêmicos e comportamentais.

As cores representam as categorias de desempenho acadêmico:

- **Verde:** alto desempenho  
- **Amarelo:** desempenho médio  
- **Vermelho:** baixo desempenho  

Observou-se a formação de comunidades com maior concentração de alunos de desempenho semelhante, especialmente entre alunos de alto e baixo desempenho, indicando que estudantes com histórico acadêmico e hábitos parecidos tendem a se agrupar.

Os alunos de desempenho médio apareceram mais distribuídos pela rede, funcionando como ponte entre diferentes grupos.

Também foram identificados alguns nós isolados, sugerindo alunos com perfis acadêmicos ou comportamentais atípicos em relação ao restante da base.
"""

for i, comunidade in enumerate(comunidades[:5]):
    print(f'\nComunidade {i}')

    print(
        dados.loc[list(comunidade), 'categoria']
        .value_counts()
    )

print(
    dados.groupby('categoria')[
        ['G1', 'G2', 'studytime','failures','absences','goout', 'freetime', 'Walc', 'Dalc']
    ].mean()
)

"""A divisão em comunidades mostrou grupos mais homogêneos, com destaque para comunidades predominantemente formadas por alunos de **baixo desempenho** e uma comunidade majoritariamente composta por alunos de **alto desempenho**.

A análise das médias indicou que alunos de baixo desempenho apresentaram maior número de **reprovações anteriores (`failures`)**, maior quantidade de **faltas (`absences`)** e maior frequência de atividades sociais (`goout`) e consumo de álcool (`Walc` e `Dalc`).

Já alunos de alto desempenho apresentaram menor histórico de reprovações e faltas, além de leve aumento no tempo de estudo (`studytime`).

**Grafo 02: Desempenho sem basear nas notas (G1 e G2)**

Os grupos mostraram diferenças importantes no desempenho acadêmico dos estudantes, principalmente sobre as variáveis G1 e G2, que apresentam as notas do primeiro e segundo período, respectivamente.

A efeito de comparação, criamos um outro grafo apenas com as variáveis comportamentais, para ver o quanto elas implicam sobre o desempenho final dos alunos.
"""

features = dados[['studytime',
                  'failures',
                  'absences',
                  'goout',
                  'freetime',
                  'Walc',
                  'Dalc']]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(features)

from sklearn.metrics.pairwise import cosine_similarity

similaridade = cosine_similarity(X)

G = nx.Graph()

for i in range(len(dados)):
    G.add_node(i)

threshold = 0.75

for i in range(len(dados)):
    for j in range(i+1, len(dados)):
        if similaridade[i][j] > threshold:
            G.add_edge(i, j, weight=similaridade[i][j])

from networkx.algorithms.community import greedy_modularity_communities

comunidades = list(greedy_modularity_communities(G))

cores = []

for node in G.nodes():
    categoria = dados.loc[node, 'categoria']

    if categoria == 'Baixo':
        cores.append('red')
    elif categoria == 'Médio':
        cores.append('yellow')
    else:
        cores.append('green')

plt.figure(figsize=(12,8))

nx.draw(
    G,
    node_color=cores,
    node_size=40,
    with_labels=False
)

plt.show()

for i, comunidade in enumerate(comunidades[:5]):
    print(f'\nComunidade {i}')

    print(
        dados.loc[list(comunidade), 'categoria']
        .value_counts()
    )

"""**Conclusão**
A comparação entre os grafos mostrou que a inclusão de **G1 e G2** gerou comunidades mais homogêneas e melhor separação entre alunos de baixo, médio e alto desempenho, indicando forte influência do histórico acadêmico no desempenho final.

No grafo sem **G1 e G2**, observou-se maior mistura entre as categorias, sugerindo que variáveis comportamentais como faltas, reprovações, tempo de estudo e hábitos sociais possuem relação com o desempenho, mas menor capacidade de separação quando analisadas isoladamente.

Assim, conclui-se que o histórico de notas anteriores é o principal fator na formação dos agrupamentos, enquanto variáveis comportamentais atuam como fatores complementares.
"""

#Grafo com nó por failures (reprovações)
tamanho_nos = dados['failures'] * 200 + 40

nx.draw(
    G,
    node_color=cores,
    node_size=tamanho_nos,
    with_labels=False
)

#Gráfico tamanho dos nós por absences (faltas)
tamanho_nos = dados['absences'] * 15 + 30

nx.draw(
    G,
    node_color=cores,
    node_size=tamanho_nos,
    with_labels=False
)

#calculo do grau
graus = dict(G.degree())
dados['grau'] = dados.index.map(graus)

print(
    dados.groupby('categoria')['grau'].mean()
)

dados.boxplot(column='grau', by='categoria')
plt.show()

print(pd.crosstab(dados['higher'], dados['categoria']))

print(pd.crosstab(dados['paid'], dados['categoria']))

import seaborn as sns
import matplotlib.pyplot as plt

cols = ['G1','G2','G3','studytime','failures','absences','goout','Walc','Dalc']

corr = dados[cols].corr()

plt.figure(figsize=(10,8))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlação entre variáveis acadêmicas e comportamentais')
plt.show()